import { Prisma, PrismaClient } from '@prisma/client'
import bcrypt from 'bcrypt'

export const firstNames = [
  'Алексей',
  'Мария',
  'Иван',
  'Екатерина',
  'Павел',
  'Анна',
  'Сергей',
  'Ольга',
  'Дмитрий',
  'Наталья',
  'Андрей',
  'Елена',
  'Михаил',
  'Татьяна',
  'Владимир',
  'Ирина',
  'Никита',
  'Светлана',
  'Юрий',
  'Людмила',
  'Артур',
  'Алёна',
  'Роман',
  'Вероника',
  'Евгений',
  'Дарья',
  'Борис',
  'Анастасия',
  'Олег',
  'Ксения',
  'Григорий',
  'Марина',
  'Тимофей',
  'Яна',
  'Константин',
  'Зоя',
  'Леонид',
  'Полина',
  'Виктор',
  'Нина',
  'Степан',
  'Лариса',
  'Георгий',
  'Валентина',
  'Руслан',
  'Жанна',
  'Василий',
  'Вера',
  'Арсений',
  'Оксана',
  'Матвей',
  'Галина',
  'Антон',
  'Евгения',
  'Максим',
  'Юлия',
  'Кирилл',
  'Любовь',
  'Ярослав',
  'Валерия',
  'Илья',
  'Алиса',
  'Станислав',
  'Агата',
  'Николай',
  'Виолетта',
  'Игнат',
  'Эльвира',
  'Тарас',
  'Инна',
  'Пётр',
  'Карина',
  'Даниил',
  'Милана',
  'Виталий',
  'Диана',
  'Артемий',
  'Есения',
  'Семён',
  'Любава',
  'Геннадий',
  'Ульяна',
  'Захар',
  'Василиса',
  'Лев',
  'Марфа',
  'Эдуард',
  'Софья',
  'Владислав',
  'Аделина',
  'Родион',
  'Арина',
  'Святослав',
  'Ярослава',
  'Прохор',
  'Снежана',
  'Богдан',
  'Кристина',
  'Тимур',
  'Ангелина',
]
export const lastNames = [
  'Иванов',
  'Петров',
  'Сидоров',
  'Смирнов',
  'Кузнецов',
  'Попов',
  'Васильев',
  'Соколов',
  'Михайлов',
  'Новиков',
  'Фёдоров',
  'Морозов',
  'Волков',
  'Алексеев',
  'Лебедев',
  'Семенов',
  'Егоров',
  'Павлов',
  'Козлов',
  'Степанов',
  'Николаев',
  'Орлов',
  'Андреев',
  'Макаров',
  'Никитин',
  'Захаров',
  'Зайцев',
  'Соловьёв',
  'Борисов',
  'Яковлев',
  'Григорьев',
  'Романов',
  'Виноградов',
  'Климов',
  'Белов',
  'Тарасов',
  'Беляев',
  'Комаров',
  'Лукин',
  'Савельев',
  'Жуков',
  'Крылов',
  'Карпов',
  'Щербаков',
  'Куликов',
  'Агафонов',
  'Поляков',
  'Быков',
  'Сергеев',
  'Королёв',
  'Гусев',
  'Фролов',
  'Дьяков',
  'Герасимов',
  'Пономарёв',
  'Голубев',
  'Калинин',
  'Курочкин',
  'Горбунов',
  'Ларионов',
  'Молчанов',
  'Соболев',
  'Буров',
  'Мартынов',
  'Ершов',
  'Носков',
  'Краснов',
  'Фомин',
  'Мельников',
  'Анисимов',
  'Тимофеев',
  'Гаврилов',
  'Коновалов',
  'Данилов',
  'Сафонов',
  'Шестаков',
  'Шилов',
  'Медведев',
  'Демидов',
  'Никифоров',
  'Матвеев',
  'Горшков',
  'Овчинников',
  'Цветков',
  'Трофимов',
  'Нечаев',
  'Лыткин',
  'Устинов',
  'Брагин',
  'Грачёв',
  'Мухин',
  'Артамонов',
  'Бобров',
  'Костин',
  'Чернов',
  'Субботин',
  'Журавлёв',
  'Пахомов',
  'Прохоров',
  'Наумов',
]

const prisma = new PrismaClient()

async function getUsers(): Promise<Prisma.UserCreateManyInput[]> {
  return [
    {
      firstName: 'Максим',
      password: await bcrypt.hash('admin', 10),
      role: 'ADMIN',
      passwordRequired: true,
    },
    {
      firstName: 'Саша',
      password: await bcrypt.hash('owner', 10),
      role: 'OWNER',
      passwordRequired: true,
    },
    {
      firstName: 'Настя',
      password: await bcrypt.hash('owner', 10),
      role: 'OWNER',
      passwordRequired: true,
    },
    {
      firstName: 'Рита',
      password: await bcrypt.hash('manager', 10),
      role: 'MANAGER',
      passwordRequired: true,
    },
    {
      firstName: 'Маша',
      password: await bcrypt.hash('manager', 10),
      role: 'MANAGER',
      passwordRequired: true,
    },
    {
      firstName: 'Наташа',
      password: await bcrypt.hash('teacher', 10),
      role: 'TEACHER',
      passwordRequired: false,
    },
    {
      firstName: 'Федя',
      password: await bcrypt.hash('teacher', 10),
      role: 'TEACHER',
      passwordRequired: false,
    },
  ]
}
async function getCourses() {
  const courses: Prisma.CourseCreateManyInput[] = [
    {
      name: 'Python Start 1',
    },
    {
      name: 'Python Start 2',
    },
    {
      name: 'Python Pro 1',
    },
    {
      name: 'Python Pro 2',
    },
    {
      name: 'Visual Programming',
    },
    {
      name: 'Unity',
    },
  ]
  return courses
}

export async function main() {
  if ((await prisma.user.count()) == 0) await prisma.user.createMany({ data: await getUsers() })

  if ((await prisma.course.count()) == 0)
    await prisma.course.createMany({ data: await getCourses() })
}

main()
